import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Searcher from "@/components/Searcher/Searcher";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import Poap from "@/components/Poap/Poap";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [poaps, setPoaps] = useState<poap[]>([]);

  return (
    <>
      <Head>
        <title>POAP Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ToastContainer />
        <Searcher setPoaps={setPoaps} />
        {poaps.length > 0 && (
          <section>
            {poaps.map((poap) => {
              return (
                <Poap
                  key={poap.tokenId}
                  name={poap.event.name}
                  image_url={poap.event.image_url + "?size=small"}
                  id_token={poap.tokenId}
                  id={poap.event.id}
                />
              );
            })}
          </section>
        )}
      </main>
    </>
  );
}
